{{- $secretName := default .Release.Name }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mysql-mvn.fullname" . }}
  labels:
    {{- include "mysql-mvn.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "mysql-mvn.fullname" . }}
  selector:
    matchLabels:
      {{- include "mysql-mvn.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mysql-mvn.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mysql-mvn.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}-secrets
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}-secrets
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}-secrets
                  key: MYSQL_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}-secrets
                  key: MYSQL_ROOT_PASSWORD
            {{- range $key, $val := .Values.env.normal }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end}}
          {{- if .Values.args }}
          args:
            {{- range .Values.args }}
            - {{ . }}
            {{- end }}
          {{- end }}
          volumeMounts:
            {{- range $key, $val := .Values.mountPath }}
            - name: {{ $key }}
              mountPath: {{ $val }}
            {{- end }}
          # - name: mysql-pvc
          #   mountPath: /var/lib/mysql
      volumes:
        {{- $chartName := include "mysql-mvn.fullname" . -}}
        {{- range $key, $val := .Values.mountPath }}
        - name: {{ $key }}
          persistentVolumeClaim:
            claimName: {{ $chartName }}
        {{- end }}
      # - name: mysql-pvc
      #   persistentVolumeClaim:
      #     claimName: {{ include "mysql-mvn.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
