apiVersion: v2
name: wp-webapp
description: A Helm chart Wordpress customize for Kubernetes

type: application

version: 0.1.5

appVersion: "1.16.0"

dependencies:
- name: mysql-mvn
  version: 0.1.5
  repository: "https://mvn-ngoctran2-dn.github.io/helm-chart-test/"